const products = [
  {
    name: 'Potion',
    price: 299,
    description: 'Restores HP that have been lost in battle by 20 HP.',
    imageUrl: '../images/products/Potion.png',
    quantity: 100,
    category: 'Potions',
  },
  {
    name: 'Super Potion',
    price: 699,
    description: 'Restores HP that have been lost in battle by 50 HP.',
    imageUrl: '../images/products/SuperPotion.png',
    quantity: 100,
    category: 'Potions',
  },
  {
    name: 'Hyper Potion',
    price: 1499,
    description: 'Restores HP that have been lost in battle by 200 HP.',
    imageUrl: '../images/products/HyperPotion.png',
    quantity: 100,
    category: 'Potions',
  },
  {
    name: 'Max Potion',
    price: 2499,
    description: 'Fully restores HP that have been lost in battle.',
    imageUrl: '../images/products/MaxPotion.png',
    quantity: 100,
    category: 'Potions',
  },
  {
    name: 'Full Restore',
    price: 2999,
    description: 'Fully restores HP and cures all ailments, such as poisoning.',
    imageUrl: '../images/products/FullRestore.png',
    quantity: 100,
    category: 'Potions',
  },
  {
    name: 'Poké Ball',
    price: 199,
    description: 'A Ball thrown at wild Pokémon to catch them.',
    imageUrl: '../images/products/PokéBall.webp',
    quantity: 100,
    category: 'Poké Balls',
  },
  {
    name: 'Great Ball',
    price: 599,
    description:
      'A Ball for catching wild Pokémon. More effective than a Poké Ball.',
    imageUrl: '../images/products/GreatBall.png',
    quantity: 100,
    category: 'Poké Balls',
  },
  {
    name: 'Ultra Ball',
    price: 1199,
    description:
      'A Ball for catching wild Pokémon. More effective than a Great Ball.',
    imageUrl: '../images/products/UltraBall.png',
    quantity: 100,
    category: 'Poké Balls',
  },
  {
    name: 'Master Ball',
    price: 1000000,
    description: 'A Ball that captures any wild Pokémon without fail.',
    imageUrl: '../images/products/MasterBall.png',
    quantity: 1,
    category: 'Poké Balls',
  },
  {
    name: 'Dusk Ball',
    price: 999,
    description:
      'A somewhat different Poké Ball that makes it easier to catch wild Pokémon at night or in dark places like caves.',
    imageUrl: '../images/products/DuskBall.png',
    quantity: 100,
    category: 'Poké Balls',
  },
  {
    name: 'X Attack',
    price: 499,
    description: 'Temporarily increases Attack power for one battle.',
    imageUrl: '../images/products/XAttack.webp',
    quantity: 100,
    category: 'Battle Items',
  },
  {
    name: 'X Defense',
    price: 550,
    description: 'Temporarily increases Defense for one battle.',
    imageUrl: '../images/products/XDefense.png',
    quantity: 100,
    category: 'Battle Items',
  },
  {
    name: 'X Speed',
    price: 350,
    description: 'Temporarily increases Speed for one battle.',
    imageUrl: '../images/products/XSpeed.png',
    quantity: 100,
    category: 'Battle Items',
  },
  {
    name: 'Dire Hit',
    price: 650,
    description:
      'Temporarily heightens the probability of scoring critical hits in one battle.',
    imageUrl: '../images/products/DireHit.webp',
    quantity: 100,
    category: 'Battle Items',
  },
  {
    name: 'X Accuracy',
    price: 950,
    description: 'Temporarily heightens accuracy for one battle.',
    imageUrl: '../images/products/XAccuracy.png',
    quantity: 100,
    category: 'Battle Items',
  },
];

module.exports = products;
