const users = [
  {
    firstName: 'Ash',
    lastName: 'Ketchum',
    email: 'a_ketchum@pokemon.com',
    password: 'pika123',
    street: '123 Main Street',
    city: 'Pallet Town',
    state: 'Kanto',
    zip: '12345',
    isAdmin: true,
  },
  {
    firstName: 'Inuko',
    lastName: 'Inuyama',
    email: 'inuko_inuyama@gmail.com',
    password: 'password123',
    street: '13101 Bellaria Cir',
    city: 'Windermere',
    state: 'FL',
    zip: '34786',
    isAdmin: false,
  },
  {
    firstName: 'Yuji',
    lastName: 'Ueda',
    email: 'y.ueda@hotmail.com',
    password: 'Maddie321',
    street: '1759 W DESPERADO Way',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85085',
    isAdmin: false,
  },
  {
    firstName: 'Amy',
    lastName: 'Rogers',
    email: 'amy.rogers@pokeusa.com',
    password: 'Admin1234!',
    street: '490 Monroe St',
    city: 'MONTEREY',
    state: 'CA',
    zip: '93940',
    isAdmin: false,
  },
  {
    firstName: 'Serena',
    lastName: 'Kalos',
    email: 'serena_kalos@yahoo.com',
    password: 'Fushigi!!',
    street: '4450 N 53RD St #5',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85018',
    isAdmin: false,
  },
  {
    firstName: 'Yuki',
    lastName: 'Kaji',
    email: 'yuki_kaji@pokeco.com',
    password: 'passwordpoke34!',
    street: '6900 E Riverside Dr #2',
    city: 'Austin',
    state: 'TX',
    zip: '78741',
    isAdmin: false,
  },
  {
    firstName: 'Rotom',
    lastName: 'Pokedex',
    email: 'rotom@yahoo.com',
    password: 'Alola123',
    street: '10521 Orange Grove Dr',
    city: 'TAMPA',
    state: 'FL',
    zip: '33618',
    isAdmin: false,
  },
  {
    firstName: 'Celmont',
    lastName: 'Dedenne',
    email: 'celemont-dednne@aol.com',
    password: 'Lana123',
    street: '3603 E Knollwood St',
    city: 'TAMPA',
    state: 'FL',
    zip: '33610',
    isAdmin: false,
  },
  {
    firstName: 'Kiawe',
    lastName: 'Ishikawa',
    email: 'kishikawa@yahoo.com',
    password: 'Marc123!',
    street: '7605 E 109th Ter',
    city: 'Kansas City',
    state: 'MO',
    zip: '64134',
    isAdmin: false,
  },
];

module.exports = users;
